name: env_var_example
description: Example for env_var
version: 1.0.0
publish_to: none
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  env_var:
    path: ../
dev_dependencies:
  build_runner: ^2.4.0
