name: env_annotation
description: Annotation generator for @Env
version: 1.0.0
homepage: https://github.com/PROGrand/env_annotation
repository: https://github.com/PROGrand/env_annotation
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  analyzer: ^14.4.0
  build: ^4.0.11
  dotenv: ^4.2.0
  meta: ^1.19.0
  source_gen: ^4.3.0
  universal_io: ^2.3.1
dev_dependencies:
  lints: ^6.1.0
  build_runner: ^2.4.0
  build_test: ^3.5.20
